/* Generated by Yosys 0.41+126 (git sha1 855ac285f, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */
// https://github.com/adhiiiii/Hardware-Design---VLSI/blob/main/Readme.md 
// Audhivishnu K
module uart(din, wr_en, clk_5m, tx, tx_busy, rx, rdy, rdy_clr, dout);
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire [6:0] _000_;
  wire [10:0] _001_;
  wire _004_;
  wire [7:0] _007_;
  wire [3:0] _009_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire [2:0] _057_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [15:0] \_131_$func$synth_uart_audhi.v:557$181.b ;
  wire [1:0] \_131_$func$synth_uart_audhi.v:557$181.s ;
  wire [7:0] \_133_$func$synth_uart_audhi.v:572$182.b ;
  wire [1:0] \_133_$func$synth_uart_audhi.v:572$182.s ;
  wire [3:0] \_136_$func$synth_uart_audhi.v:590$176.$result ;
  wire [11:0] \_136_$func$synth_uart_audhi.v:590$183.b ;
  wire [2:0] \_136_$func$synth_uart_audhi.v:590$183.s ;
  wire [1:0] \_140_$func$synth_uart_audhi.v:609$177.$result ;
  wire [5:0] \_140_$func$synth_uart_audhi.v:609$184.b ;
  wire [2:0] \_140_$func$synth_uart_audhi.v:609$184.s ;
  wire \_174_$func$synth_uart_audhi.v:662$178.$result ;
  wire [2:0] \_174_$func$synth_uart_audhi.v:662$185.b ;
  wire [2:0] \_174_$func$synth_uart_audhi.v:662$185.s ;
  wire [5:0] \_179_$func$synth_uart_audhi.v:680$186.b ;
  wire [1:0] \_179_$func$synth_uart_audhi.v:680$186.s ;
  wire [1:0] \_182_$func$synth_uart_audhi.v:700$180.$result ;
  wire [7:0] \_182_$func$synth_uart_audhi.v:700$187.b ;
  wire [3:0] \_182_$func$synth_uart_audhi.v:700$187.s ;
  input clk_5m;
  wire clk_5m;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  output rdy;
  wire rdy;
  input rdy_clr;
  wire rdy_clr;
  input rx;
  wire rx;
  output tx;
  wire tx;
  output tx_busy;
  wire tx_busy;
  wire \uart_baud.clk_5m ;
  reg [6:0] \uart_baud.rx_acc  = 7'h00;
  reg [10:0] \uart_baud.tx_acc  = 11'h000;
  reg [3:0] \uart_rx.bitpos  = 4'h0;
  wire \uart_rx.clk_5m ;
  reg [7:0] \uart_rx.data  = 8'h00;
  reg \uart_rx.rdy  = 1'h0;
  wire \uart_rx.rdy_clr ;
  wire \uart_rx.rx ;
  reg [3:0] \uart_rx.sample  = 4'h0;
  reg [7:0] \uart_rx.scratch  = 8'h00;
  reg [1:0] \uart_rx.state  = 2'h0;
  reg [2:0] \uart_tx.bitpos  = 3'h0;
  wire \uart_tx.clk_5m ;
  reg [7:0] \uart_tx.data  = 8'h00;
  wire [7:0] \uart_tx.din ;
  reg [1:0] \uart_tx.state  = 2'h0;
  reg \uart_tx.tx  = 1'h1;
  wire \uart_tx.tx_busy ;
  wire \uart_tx.wr_en ;
  input wr_en;
  wire wr_en;
  assign _000_[0] = ~\uart_baud.rx_acc [0];
  assign _057_[0] = ~\uart_tx.bitpos [0];
  assign _009_[0] = ~\uart_rx.bitpos [0];
  assign _073_ = ~(\uart_tx.state [0] | \uart_tx.state [1]);
  assign tx_busy = ~_073_;
  assign _067_ = _073_ & wr_en;
  assign _074_ = ~(\uart_baud.tx_acc [0] | \uart_baud.tx_acc [1]);
  assign _075_ = \uart_baud.tx_acc [3] | \uart_baud.tx_acc [2];
  assign _076_ = _074_ & ~(_075_);
  assign _077_ = \uart_baud.tx_acc [4] | \uart_baud.tx_acc [5];
  assign _078_ = \uart_baud.tx_acc [7] | \uart_baud.tx_acc [6];
  assign _079_ = _078_ | _077_;
  assign _080_ = _076_ & ~(_079_);
  assign _081_ = \uart_baud.tx_acc [9] | \uart_baud.tx_acc [8];
  assign _082_ = _081_ | \uart_baud.tx_acc [10];
  assign _083_ = _082_ | ~(_080_);
  assign _084_ = ~(\uart_tx.state [0] & \uart_tx.state [1]);
  assign _085_ = _083_ & ~(_084_);
  assign _086_ = \uart_tx.state [1] & ~(\uart_tx.state [0]);
  assign _087_ = ~_086_;
  assign _088_ = _087_ | ~(_083_);
  assign _089_ = _088_ & ~(_085_);
  assign _090_ = \uart_tx.state [1] | ~(\uart_tx.state [0]);
  assign _091_ = _083_ & ~(_090_);
  assign _092_ = _080_ & ~(_082_);
  assign _093_ = ~\uart_tx.bitpos [2];
  assign _094_ = ~(\uart_tx.bitpos [1] & \uart_tx.bitpos [0]);
  assign _095_ = _094_ | _093_;
  assign _096_ = ~(_095_ & _092_);
  assign _097_ = _086_ & ~(_096_);
  assign _098_ = _097_ | _091_;
  assign _099_ = _089_ & ~(_098_);
  assign _100_ = _073_ & ~(wr_en);
  assign _101_ = _084_ & ~(_073_);
  assign _102_ = _086_ | ~(_090_);
  assign _103_ = _101_ & ~(_102_);
  assign _104_ = _103_ | _100_;
  assign _068_ = _099_ & ~(_104_);
  assign _105_ = _088_ & ~(_100_);
  assign _106_ = _092_ & ~(_095_);
  assign _107_ = _086_ ? _106_ : tx_busy;
  assign _069_ = _105_ & ~(_107_);
  assign _108_ = _084_ & ~(_086_);
  assign _109_ = _090_ ? _108_ : _083_;
  assign _070_ = _089_ & ~(_109_);
  assign _110_ = \uart_baud.rx_acc [1] | ~(\uart_baud.rx_acc [0]);
  assign _111_ = \uart_baud.rx_acc [3] | \uart_baud.rx_acc [2];
  assign _112_ = _111_ | _110_;
  assign _113_ = \uart_baud.rx_acc [5] | \uart_baud.rx_acc [4];
  assign _114_ = _113_ | ~(\uart_baud.rx_acc [6]);
  assign _071_ = _114_ | _112_;
  assign _001_[0] = ~\uart_baud.tx_acc [0];
  assign _115_ = \uart_baud.tx_acc [1] | ~(\uart_baud.tx_acc [0]);
  assign _116_ = _115_ | _075_;
  assign _117_ = \uart_baud.tx_acc [5] | ~(\uart_baud.tx_acc [4]);
  assign _118_ = _117_ | _078_;
  assign _119_ = _118_ | _116_;
  assign _120_ = _081_ | ~(\uart_baud.tx_acc [10]);
  assign _072_ = _120_ | _119_;
  assign \_140_$func$synth_uart_audhi.v:609$177.$result [0] = ~(\uart_rx.state [1] | \uart_rx.state [0]);
  assign _121_ = \uart_rx.sample [1] | \uart_rx.sample [0];
  assign _122_ = \uart_rx.sample [3] & ~(\uart_rx.sample [2]);
  assign _123_ = _122_ & ~(_121_);
  assign \_140_$func$synth_uart_audhi.v:609$177.$result [1] = \uart_rx.state [0] & ~(\uart_rx.state [1]);
  assign _124_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(_123_);
  assign _125_ = \uart_rx.sample [1] & \uart_rx.sample [0];
  assign _126_ = ~(\uart_rx.sample [2] & \uart_rx.sample [3]);
  assign _127_ = _125_ & ~(_126_);
  assign _128_ = _127_ | ~(\_140_$func$synth_uart_audhi.v:609$177.$result [0]);
  assign _129_ = _128_ & ~(_124_);
  assign _130_ = ~(\_140_$func$synth_uart_audhi.v:609$177.$result [1] | \_140_$func$synth_uart_audhi.v:609$177.$result [0]);
  assign _131_ = \uart_baud.rx_acc [1] | \uart_baud.rx_acc [0];
  assign _132_ = _131_ | _111_;
  assign _133_ = _113_ | \uart_baud.rx_acc [6];
  assign _134_ = _133_ | _132_;
  assign _135_ = _134_ | _130_;
  assign _018_ = _129_ & ~(_135_);
  assign _136_ = ~_134_;
  assign _137_ = ~rx;
  assign _138_ = ~\uart_rx.sample [3];
  assign _139_ = _138_ & ~(_123_);
  assign _140_ = _137_ & ~(_139_);
  assign _141_ = ~(_140_ | _127_);
  assign _142_ = \uart_rx.state [0] | ~(\uart_rx.state [1]);
  assign _143_ = _142_ | _141_;
  assign _019_ = _136_ & ~(_143_);
  assign _144_ = ~(\uart_rx.bitpos [1] | \uart_rx.bitpos [0]);
  assign _145_ = \uart_rx.bitpos [3] & ~(\uart_rx.bitpos [2]);
  assign _146_ = ~(_145_ & _144_);
  assign _147_ = _127_ & ~(_146_);
  assign _148_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(_147_);
  assign _149_ = _128_ & ~(_148_);
  assign _150_ = _141_ & ~(_142_);
  assign _151_ = _150_ | _134_;
  assign _020_ = _149_ & ~(_151_);
  assign _152_ = \uart_rx.sample [2] | \uart_rx.sample [3];
  assign _153_ = _152_ | _121_;
  assign _154_ = _153_ | _137_;
  assign _155_ = _154_ | _127_;
  assign _156_ = \_140_$func$synth_uart_audhi.v:609$177.$result [0] & ~(_155_);
  assign _157_ = \uart_rx.state [1] & \uart_rx.state [0];
  assign _158_ = _157_ | _156_;
  assign _021_ = _136_ & ~(_158_);
  assign _159_ = _141_ & ~(\uart_rx.sample [0]);
  assign _160_ = _127_ | \uart_rx.sample [0];
  assign _161_ = \_140_$func$synth_uart_audhi.v:609$177.$result [0] & ~(_160_);
  assign _162_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(\uart_rx.sample [0]);
  assign _163_ = _162_ | _161_;
  assign \_136_$func$synth_uart_audhi.v:590$176.$result [0] = _130_ ? _159_ : _163_;
  assign _164_ = ~(\uart_rx.sample [1] ^ \uart_rx.sample [0]);
  assign _165_ = _141_ & ~(_164_);
  assign _166_ = _164_ | _127_;
  assign _167_ = \_140_$func$synth_uart_audhi.v:609$177.$result [0] & ~(_166_);
  assign _168_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(_164_);
  assign _169_ = _168_ | _167_;
  assign \_136_$func$synth_uart_audhi.v:590$176.$result [1] = _130_ ? _165_ : _169_;
  assign _170_ = ~(_125_ ^ \uart_rx.sample [2]);
  assign _171_ = _141_ & ~(_170_);
  assign _172_ = _170_ | _127_;
  assign _173_ = \_140_$func$synth_uart_audhi.v:609$177.$result [0] & ~(_172_);
  assign _174_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(_170_);
  assign _175_ = _174_ | _173_;
  assign \_136_$func$synth_uart_audhi.v:590$176.$result [2] = _130_ ? _171_ : _175_;
  assign _176_ = _125_ & \uart_rx.sample [2];
  assign _177_ = _176_ ^ _138_;
  assign _178_ = _141_ & ~(_177_);
  assign _179_ = _177_ | _127_;
  assign _180_ = \_140_$func$synth_uart_audhi.v:609$177.$result [0] & ~(_179_);
  assign _181_ = \_140_$func$synth_uart_audhi.v:609$177.$result [1] & ~(_177_);
  assign _182_ = _181_ | _180_;
  assign \_136_$func$synth_uart_audhi.v:590$176.$result [3] = _130_ ? _178_ : _182_;
  assign _183_ = \uart_tx.bitpos [0] ? \uart_tx.data [1] : \uart_tx.data [0];
  assign _184_ = \uart_tx.bitpos [0] ? \uart_tx.data [3] : \uart_tx.data [2];
  assign _185_ = \uart_tx.bitpos [1] ? _184_ : _183_;
  assign _186_ = \uart_tx.bitpos [0] ? \uart_tx.data [5] : \uart_tx.data [4];
  assign _187_ = \uart_tx.bitpos [0] ? \uart_tx.data [7] : \uart_tx.data [6];
  assign _188_ = \uart_tx.bitpos [1] ? _187_ : _186_;
  assign _189_ = \uart_tx.bitpos [2] ? _188_ : _185_;
  assign \_174_$func$synth_uart_audhi.v:662$178.$result  = _086_ ? _189_ : _090_;
  assign \_182_$func$synth_uart_audhi.v:700$180.$result [0] = _086_ | _073_;
  assign \_182_$func$synth_uart_audhi.v:700$180.$result [1] = \uart_tx.state [0] ^ \uart_tx.state [1];
  assign _190_ = \uart_rx.rdy  & ~(rdy_clr);
  assign _191_ = _190_ | ~(_141_);
  assign _192_ = _142_ ? _190_ : _191_;
  assign _004_ = _134_ ? _190_ : _192_;
  assign _193_ = ~(\uart_rx.bitpos [1] ^ \uart_rx.bitpos [0]);
  assign _009_[1] = ~_193_;
  assign _194_ = \uart_rx.bitpos [1] & \uart_rx.bitpos [0];
  assign _009_[2] = _194_ ^ \uart_rx.bitpos [2];
  assign _195_ = ~\uart_rx.bitpos [2];
  assign _196_ = _194_ & ~(_195_);
  assign _009_[3] = _196_ ^ \uart_rx.bitpos [3];
  assign _001_[1] = \uart_baud.tx_acc [0] ^ \uart_baud.tx_acc [1];
  assign _197_ = \uart_baud.tx_acc [0] & \uart_baud.tx_acc [1];
  assign _001_[2] = _197_ ^ \uart_baud.tx_acc [2];
  assign _198_ = _197_ & \uart_baud.tx_acc [2];
  assign _001_[3] = _198_ ^ \uart_baud.tx_acc [3];
  assign _199_ = ~(\uart_baud.tx_acc [3] & \uart_baud.tx_acc [2]);
  assign _200_ = _197_ & ~(_199_);
  assign _001_[4] = _200_ ^ \uart_baud.tx_acc [4];
  assign _201_ = _200_ & \uart_baud.tx_acc [4];
  assign _001_[5] = _201_ ^ \uart_baud.tx_acc [5];
  assign _202_ = ~(\uart_baud.tx_acc [4] & \uart_baud.tx_acc [5]);
  assign _203_ = _202_ | ~(_200_);
  assign _001_[6] = ~(_203_ ^ \uart_baud.tx_acc [6]);
  assign _204_ = \uart_baud.tx_acc [6] & ~(_203_);
  assign _001_[7] = _204_ ^ \uart_baud.tx_acc [7];
  assign _205_ = ~(\uart_baud.tx_acc [7] & \uart_baud.tx_acc [6]);
  assign _206_ = _205_ | _202_;
  assign _207_ = _200_ & ~(_206_);
  assign _001_[8] = _207_ ^ \uart_baud.tx_acc [8];
  assign _208_ = _207_ & \uart_baud.tx_acc [8];
  assign _001_[9] = _208_ ^ \uart_baud.tx_acc [9];
  assign _209_ = ~(\uart_baud.tx_acc [9] & \uart_baud.tx_acc [8]);
  assign _210_ = _207_ & ~(_209_);
  assign _001_[10] = _210_ ^ \uart_baud.tx_acc [10];
  assign _057_[1] = \uart_tx.bitpos [1] ^ \uart_tx.bitpos [0];
  assign _057_[2] = _094_ ^ _093_;
  assign _000_[1] = \uart_baud.rx_acc [1] ^ \uart_baud.rx_acc [0];
  assign _211_ = \uart_baud.rx_acc [1] & \uart_baud.rx_acc [0];
  assign _000_[2] = _211_ ^ \uart_baud.rx_acc [2];
  assign _212_ = _211_ & \uart_baud.rx_acc [2];
  assign _000_[3] = _212_ ^ \uart_baud.rx_acc [3];
  assign _213_ = ~(\uart_baud.rx_acc [3] & \uart_baud.rx_acc [2]);
  assign _214_ = _211_ & ~(_213_);
  assign _000_[4] = _214_ ^ \uart_baud.rx_acc [4];
  assign _215_ = _214_ & \uart_baud.rx_acc [4];
  assign _000_[5] = _215_ ^ \uart_baud.rx_acc [5];
  assign _216_ = ~(\uart_baud.rx_acc [5] & \uart_baud.rx_acc [4]);
  assign _217_ = _214_ & ~(_216_);
  assign _000_[6] = _217_ ^ \uart_baud.rx_acc [6];
  assign _218_ = \uart_rx.bitpos [1] | \uart_rx.bitpos [0];
  assign _219_ = _144_ ^ _195_;
  assign _220_ = _144_ ^ _219_;
  assign _221_ = _220_ & ~(_218_);
  assign _222_ = ~(_144_ & _195_);
  assign _223_ = _144_ & ~(_219_);
  assign _224_ = ~(_223_ ^ _222_);
  assign _225_ = _221_ & ~(_224_);
  assign _226_ = _219_ | _009_[1];
  assign _227_ = _226_ | _222_;
  assign _228_ = _009_[0] & ~(_227_);
  assign _229_ = _222_ ? _225_ : _228_;
  assign _230_ = \uart_rx.scratch [0] & ~(_229_);
  assign _231_ = _193_ ^ \uart_rx.bitpos [0];
  assign _232_ = \uart_rx.bitpos [0] | ~(rx);
  assign _233_ = _232_ | ~(_231_);
  assign _234_ = _220_ & ~(_233_);
  assign _235_ = _234_ & ~(_224_);
  assign _236_ = _227_ | _137_;
  assign _237_ = _009_[0] & ~(_236_);
  assign _238_ = _222_ ? _235_ : _237_;
  assign _007_[0] = _238_ | _230_;
  assign _239_ = ~(_144_ ^ _219_);
  assign _240_ = \uart_rx.bitpos [1] | ~(\uart_rx.bitpos [0]);
  assign _241_ = _240_ | _239_;
  assign _242_ = _241_ | _224_;
  assign _243_ = _222_ & ~(_242_);
  assign _244_ = \uart_rx.scratch [1] & ~(_243_);
  assign _245_ = ~(rx & \uart_rx.bitpos [0]);
  assign _246_ = _245_ | ~(_231_);
  assign _247_ = _246_ | _239_;
  assign _248_ = _247_ | _224_;
  assign _249_ = _222_ & ~(_248_);
  assign _007_[1] = _249_ | _244_;
  assign _250_ = \uart_rx.bitpos [0] | ~(\uart_rx.bitpos [1]);
  assign _251_ = _250_ | _239_;
  assign _252_ = _251_ | _224_;
  assign _253_ = _222_ & ~(_252_);
  assign _254_ = \uart_rx.scratch [2] & ~(_253_);
  assign _255_ = _232_ | _231_;
  assign _256_ = _255_ | _239_;
  assign _257_ = _256_ | _224_;
  assign _258_ = _222_ & ~(_257_);
  assign _007_[2] = _258_ | _254_;
  assign _259_ = ~(\uart_rx.bitpos [1] & \uart_rx.bitpos [0]);
  assign _260_ = _259_ | _239_;
  assign _261_ = _260_ | _224_;
  assign _262_ = _222_ & ~(_261_);
  assign _263_ = \uart_rx.scratch [3] & ~(_262_);
  assign _264_ = _245_ | _231_;
  assign _265_ = _264_ | _239_;
  assign _266_ = _265_ | _224_;
  assign _267_ = _222_ & ~(_266_);
  assign _007_[3] = _267_ | _263_;
  assign _268_ = _220_ | _218_;
  assign _269_ = _268_ | _224_;
  assign _270_ = _222_ & ~(_269_);
  assign _271_ = \uart_rx.scratch [4] & ~(_270_);
  assign _272_ = _233_ | _220_;
  assign _273_ = _272_ | _224_;
  assign _274_ = _222_ & ~(_273_);
  assign _007_[4] = _274_ | _271_;
  assign _275_ = _240_ | _220_;
  assign _276_ = _275_ | _224_;
  assign _277_ = _222_ & ~(_276_);
  assign _278_ = \uart_rx.scratch [5] & ~(_277_);
  assign _279_ = _246_ | _220_;
  assign _280_ = _279_ | _224_;
  assign _281_ = _222_ & ~(_280_);
  assign _007_[5] = _281_ | _278_;
  assign _282_ = _250_ | _220_;
  assign _283_ = _282_ | _224_;
  assign _284_ = _222_ & ~(_283_);
  assign _285_ = \uart_rx.scratch [6] & ~(_284_);
  assign _286_ = _255_ | _220_;
  assign _287_ = _286_ | _224_;
  assign _288_ = _222_ & ~(_287_);
  assign _007_[6] = _288_ | _285_;
  assign _289_ = _259_ | _220_;
  assign _290_ = _289_ | _224_;
  assign _291_ = _222_ & ~(_290_);
  assign _292_ = \uart_rx.scratch [7] & ~(_291_);
  assign _293_ = _264_ | _220_;
  assign _294_ = _293_ | _224_;
  assign _295_ = _222_ & ~(_294_);
  assign _007_[7] = _295_ | _292_;
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [0] <= 1'h0;
    else \uart_baud.tx_acc [0] <= _001_[0];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [1] <= 1'h0;
    else \uart_baud.tx_acc [1] <= _001_[1];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [2] <= 1'h0;
    else \uart_baud.tx_acc [2] <= _001_[2];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [3] <= 1'h0;
    else \uart_baud.tx_acc [3] <= _001_[3];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [4] <= 1'h0;
    else \uart_baud.tx_acc [4] <= _001_[4];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [5] <= 1'h0;
    else \uart_baud.tx_acc [5] <= _001_[5];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [6] <= 1'h0;
    else \uart_baud.tx_acc [6] <= _001_[6];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [7] <= 1'h0;
    else \uart_baud.tx_acc [7] <= _001_[7];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [8] <= 1'h0;
    else \uart_baud.tx_acc [8] <= _001_[8];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [9] <= 1'h0;
    else \uart_baud.tx_acc [9] <= _001_[9];
  always @(posedge clk_5m)
    if (!_072_) \uart_baud.tx_acc [10] <= 1'h0;
    else \uart_baud.tx_acc [10] <= _001_[10];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [0] <= 1'h0;
    else \uart_baud.rx_acc [0] <= _000_[0];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [1] <= 1'h0;
    else \uart_baud.rx_acc [1] <= _000_[1];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [2] <= 1'h0;
    else \uart_baud.rx_acc [2] <= _000_[2];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [3] <= 1'h0;
    else \uart_baud.rx_acc [3] <= _000_[3];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [4] <= 1'h0;
    else \uart_baud.rx_acc [4] <= _000_[4];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [5] <= 1'h0;
    else \uart_baud.rx_acc [5] <= _000_[5];
  always @(posedge clk_5m)
    if (!_071_) \uart_baud.rx_acc [6] <= 1'h0;
    else \uart_baud.rx_acc [6] <= _000_[6];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [0] <= \uart_rx.scratch [0];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [1] <= \uart_rx.scratch [1];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [2] <= \uart_rx.scratch [2];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [3] <= \uart_rx.scratch [3];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [4] <= \uart_rx.scratch [4];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [5] <= \uart_rx.scratch [5];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [6] <= \uart_rx.scratch [6];
  always @(posedge clk_5m)
    if (_019_) \uart_rx.data [7] <= \uart_rx.scratch [7];
  always @(posedge clk_5m)
    if (_020_) \uart_rx.state [0] <= \_140_$func$synth_uart_audhi.v:609$177.$result [0];
  always @(posedge clk_5m)
    if (_020_) \uart_rx.state [1] <= \_140_$func$synth_uart_audhi.v:609$177.$result [1];
  always @(posedge clk_5m)
    if (_021_) \uart_rx.sample [0] <= \_136_$func$synth_uart_audhi.v:590$176.$result [0];
  always @(posedge clk_5m)
    if (_021_) \uart_rx.sample [1] <= \_136_$func$synth_uart_audhi.v:590$176.$result [1];
  always @(posedge clk_5m)
    if (_021_) \uart_rx.sample [2] <= \_136_$func$synth_uart_audhi.v:590$176.$result [2];
  always @(posedge clk_5m)
    if (_021_) \uart_rx.sample [3] <= \_136_$func$synth_uart_audhi.v:590$176.$result [3];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.bitpos [0] <= 1'h0;
      else \uart_rx.bitpos [0] <= _009_[0];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.bitpos [1] <= 1'h0;
      else \uart_rx.bitpos [1] <= _009_[1];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.bitpos [2] <= 1'h0;
      else \uart_rx.bitpos [2] <= _009_[2];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.bitpos [3] <= 1'h0;
      else \uart_rx.bitpos [3] <= _009_[3];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [0] <= din[0];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [1] <= din[1];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [2] <= din[2];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [3] <= din[3];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [4] <= din[4];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [5] <= din[5];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [6] <= din[6];
  always @(posedge clk_5m)
    if (_067_) \uart_tx.data [7] <= din[7];
  always @(posedge clk_5m)
    \uart_rx.rdy  <= _004_;
  always @(posedge clk_5m)
    if (_068_) \uart_tx.state [0] <= \_182_$func$synth_uart_audhi.v:700$180.$result [0];
  always @(posedge clk_5m)
    if (_068_) \uart_tx.state [1] <= \_182_$func$synth_uart_audhi.v:700$180.$result [1];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [0] <= 1'h0;
      else \uart_rx.scratch [0] <= _007_[0];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [1] <= 1'h0;
      else \uart_rx.scratch [1] <= _007_[1];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [2] <= 1'h0;
      else \uart_rx.scratch [2] <= _007_[2];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [3] <= 1'h0;
      else \uart_rx.scratch [3] <= _007_[3];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [4] <= 1'h0;
      else \uart_rx.scratch [4] <= _007_[4];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [5] <= 1'h0;
      else \uart_rx.scratch [5] <= _007_[5];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [6] <= 1'h0;
      else \uart_rx.scratch [6] <= _007_[6];
  always @(posedge clk_5m)
    if (_018_)
      if (\_140_$func$synth_uart_audhi.v:609$177.$result [0]) \uart_rx.scratch [7] <= 1'h0;
      else \uart_rx.scratch [7] <= _007_[7];
  always @(posedge clk_5m)
    if (_070_) \uart_tx.tx  <= \_174_$func$synth_uart_audhi.v:662$178.$result ;
  always @(posedge clk_5m)
    if (_069_)
      if (_073_) \uart_tx.bitpos [0] <= 1'h0;
      else \uart_tx.bitpos [0] <= _057_[0];
  always @(posedge clk_5m)
    if (_069_)
      if (_073_) \uart_tx.bitpos [1] <= 1'h0;
      else \uart_tx.bitpos [1] <= _057_[1];
  always @(posedge clk_5m)
    if (_069_)
      if (_073_) \uart_tx.bitpos [2] <= 1'h0;
      else \uart_tx.bitpos [2] <= _057_[2];
  assign \_131_$func$synth_uart_audhi.v:557$181.b  = 16'hxxxx;
  assign \_131_$func$synth_uart_audhi.v:557$181.s  = 2'hx;
  assign \_133_$func$synth_uart_audhi.v:572$182.b  = 8'hxx;
  assign \_133_$func$synth_uart_audhi.v:572$182.s  = 2'hx;
  assign \_136_$func$synth_uart_audhi.v:590$183.b  = 12'hxxx;
  assign \_136_$func$synth_uart_audhi.v:590$183.s  = 3'hx;
  assign \_140_$func$synth_uart_audhi.v:609$184.b  = 6'hxx;
  assign \_140_$func$synth_uart_audhi.v:609$184.s  = 3'hx;
  assign \_174_$func$synth_uart_audhi.v:662$185.b  = 3'hx;
  assign \_174_$func$synth_uart_audhi.v:662$185.s  = 3'hx;
  assign \_179_$func$synth_uart_audhi.v:680$186.b  = 6'hxx;
  assign \_179_$func$synth_uart_audhi.v:680$186.s  = 2'hx;
  assign \_182_$func$synth_uart_audhi.v:700$187.b  = 8'hxx;
  assign \_182_$func$synth_uart_audhi.v:700$187.s  = 4'hx;
  assign dout = \uart_rx.data ;
  assign rdy = \uart_rx.rdy ;
  assign tx = \uart_tx.tx ;
  assign \uart_baud.clk_5m  = clk_5m;
  assign \uart_rx.clk_5m  = clk_5m;
  assign \uart_rx.rdy_clr  = rdy_clr;
  assign \uart_rx.rx  = rx;
  assign \uart_tx.clk_5m  = clk_5m;
  assign \uart_tx.din  = din;
  assign \uart_tx.tx_busy  = tx_busy;
  assign \uart_tx.wr_en  = wr_en;
endmodule
 
