/* Generated by Yosys 0.41+126 (git sha1 855ac285f, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */
// https://github.com/adhiiiii/Hardware-Design---VLSI/blob/main/Readme.md 
// Audhivishnu K
module uart(din, wr_en, clk_5m, tx, tx_busy, rx, rdy, rdy_clr, dout);
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire [6:0] _000_;
  wire [10:0] _001_;
  wire _004_;
  wire [7:0] _007_;
  wire [3:0] _009_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire [2:0] _057_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire [15:0] \_131_$func$synth_uart_audhi.v:557$181.b ;
  wire [1:0] \_131_$func$synth_uart_audhi.v:557$181.s ;
  wire [7:0] \_133_$func$synth_uart_audhi.v:572$182.b ;
  wire [1:0] \_133_$func$synth_uart_audhi.v:572$182.s ;
  wire [3:0] \_136_$func$synth_uart_audhi.v:590$176.$result ;
  wire [11:0] \_136_$func$synth_uart_audhi.v:590$183.b ;
  wire [2:0] \_136_$func$synth_uart_audhi.v:590$183.s ;
  wire [1:0] \_140_$func$synth_uart_audhi.v:609$177.$result ;
  wire [5:0] \_140_$func$synth_uart_audhi.v:609$184.b ;
  wire [2:0] \_140_$func$synth_uart_audhi.v:609$184.s ;
  wire \_174_$func$synth_uart_audhi.v:662$178.$result ;
  wire [2:0] \_174_$func$synth_uart_audhi.v:662$185.b ;
  wire [2:0] \_174_$func$synth_uart_audhi.v:662$185.s ;
  wire [5:0] \_179_$func$synth_uart_audhi.v:680$186.b ;
  wire [1:0] \_179_$func$synth_uart_audhi.v:680$186.s ;
  wire [1:0] \_182_$func$synth_uart_audhi.v:700$180.$result ;
  wire [7:0] \_182_$func$synth_uart_audhi.v:700$187.b ;
  wire [3:0] \_182_$func$synth_uart_audhi.v:700$187.s ;
  input clk_5m;
  wire clk_5m;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  wire [7:0] dout;
  output rdy;
  wire rdy;
  input rdy_clr;
  wire rdy_clr;
  input rx;
  wire rx;
  output tx;
  wire tx;
  output tx_busy;
  wire tx_busy;
  wire \uart_baud.clk_5m ;
  wire [6:0] \uart_baud.rx_acc ;
  wire [10:0] \uart_baud.tx_acc ;
  wire [3:0] \uart_rx.bitpos ;
  wire \uart_rx.clk_5m ;
  wire [7:0] \uart_rx.data ;
  wire \uart_rx.rdy ;
  wire \uart_rx.rdy_clr ;
  wire \uart_rx.rx ;
  wire [3:0] \uart_rx.sample ;
  wire [7:0] \uart_rx.scratch ;
  wire [1:0] \uart_rx.state ;
  wire [2:0] \uart_tx.bitpos ;
  wire \uart_tx.clk_5m ;
  wire [7:0] \uart_tx.data ;
  wire [7:0] \uart_tx.din ;
  wire [1:0] \uart_tx.state ;
  wire \uart_tx.tx ;
  wire \uart_tx.tx_busy ;
  wire \uart_tx.wr_en ;
  input wr_en;
  wire wr_en;
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(\uart_tx.bitpos [0]),
    .Y(_057_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _212_ (
    .A(\uart_baud.rx_acc [0]),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(\uart_rx.bitpos [0]),
    .Y(_009_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _214_ (
    .A(\uart_tx.state [0]),
    .Y(\_182_$func$synth_uart_audhi.v:700$180.$result [0])
  );
  sky130_fd_sc_hd__clkinv_1 _215_ (
    .A(\uart_baud.tx_acc [0]),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _216_ (
    .A(rx),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _217_ (
    .A(\uart_rx.rdy ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and2_0 _218_ (
    .A(\uart_rx.sample [0]),
    .B(\uart_rx.sample [1]),
    .X(_075_)
  );
  sky130_fd_sc_hd__and3_1 _219_ (
    .A(\uart_rx.sample [0]),
    .B(\uart_rx.sample [2]),
    .C(\uart_rx.sample [1]),
    .X(_076_)
  );
  sky130_fd_sc_hd__and2_0 _220_ (
    .A(\uart_rx.sample [3]),
    .B(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__o21a_1 _221_ (
    .A1(_073_),
    .A2(_076_),
    .B1(\uart_rx.sample [3]),
    .X(_078_)
  );
  sky130_fd_sc_hd__and2_0 _222_ (
    .A(\uart_rx.state [1]),
    .B(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(\uart_rx.state [1]),
    .B(_078_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(\uart_rx.sample [0]),
    .B(_079_),
    .Y(\_136_$func$synth_uart_audhi.v:590$176.$result [0])
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(\uart_rx.sample [0]),
    .B(\uart_rx.sample [1]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _226_ (
    .A(_075_),
    .B(_079_),
    .C(_081_),
    .Y(\_136_$func$synth_uart_audhi.v:590$176.$result [1])
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(\uart_rx.sample [2]),
    .B(_075_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor3_1 _228_ (
    .A(_076_),
    .B(_079_),
    .C(_082_),
    .Y(\_136_$func$synth_uart_audhi.v:590$176.$result [2])
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(\uart_rx.sample [3]),
    .B(_076_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor3_1 _230_ (
    .A(_077_),
    .B(_079_),
    .C(_083_),
    .Y(\_136_$func$synth_uart_audhi.v:590$176.$result [3])
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(\_182_$func$synth_uart_audhi.v:700$180.$result [0]),
    .B(\uart_tx.state [1]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(\uart_tx.state [0]),
    .B(\uart_tx.state [1]),
    .X(\_182_$func$synth_uart_audhi.v:700$180.$result [1])
  );
  sky130_fd_sc_hd__mux2i_1 _233_ (
    .A0(\uart_tx.data [4]),
    .A1(\uart_tx.data [5]),
    .S(\uart_tx.bitpos [0]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2b_1 _234_ (
    .A(\uart_tx.bitpos [0]),
    .B_N(\uart_tx.bitpos [1]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(\uart_tx.bitpos [0]),
    .B(\uart_tx.bitpos [1]),
    .C(\uart_tx.data [7]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o211ai_1 _236_ (
    .A1(\uart_tx.bitpos [1]),
    .A2(_085_),
    .B1(_087_),
    .C1(\uart_tx.bitpos [2]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _237_ (
    .A1(\uart_tx.data [6]),
    .A2(_086_),
    .B1(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__mux2i_1 _238_ (
    .A0(\uart_tx.data [0]),
    .A1(\uart_tx.data [1]),
    .S(\uart_tx.bitpos [0]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a31oi_1 _239_ (
    .A1(\uart_tx.bitpos [0]),
    .A2(\uart_tx.data [3]),
    .A3(\uart_tx.bitpos [1]),
    .B1(\uart_tx.bitpos [2]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(\uart_tx.bitpos [1]),
    .A2(_090_),
    .B1(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(\uart_tx.data [2]),
    .A2(_086_),
    .B1(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o31ai_1 _242_ (
    .A1(_084_),
    .A2(_089_),
    .A3(_093_),
    .B1(\_182_$func$synth_uart_audhi.v:700$180.$result [1]),
    .Y(\_174_$func$synth_uart_audhi.v:662$178.$result )
  );
  sky130_fd_sc_hd__or4_1 _243_ (
    .A(\uart_baud.rx_acc [2]),
    .B(\uart_baud.rx_acc [3]),
    .C(\uart_baud.rx_acc [4]),
    .D(\uart_baud.rx_acc [5]),
    .X(_094_)
  );
  sky130_fd_sc_hd__or4_1 _244_ (
    .A(\uart_baud.rx_acc [0]),
    .B(\uart_baud.rx_acc [6]),
    .C(\uart_baud.rx_acc [1]),
    .D(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nor3_1 _245_ (
    .A(\uart_rx.state [0]),
    .B(_080_),
    .C(_095_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o32ai_1 _246_ (
    .A1(\uart_rx.state [0]),
    .A2(_080_),
    .A3(_095_),
    .B1(_074_),
    .B2(rdy_clr),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(\uart_tx.state [0]),
    .B(\uart_tx.state [1]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _248_ (
    .A(_096_),
    .Y(tx_busy)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(\uart_rx.bitpos [1]),
    .B(\uart_rx.bitpos [0]),
    .X(_009_[1])
  );
  sky130_fd_sc_hd__and3_1 _250_ (
    .A(\uart_baud.tx_acc [0]),
    .B(\uart_baud.tx_acc [1]),
    .C(\uart_baud.tx_acc [2]),
    .X(_097_)
  );
  sky130_fd_sc_hd__and4_1 _251_ (
    .A(\uart_baud.tx_acc [0]),
    .B(\uart_baud.tx_acc [1]),
    .C(\uart_baud.tx_acc [2]),
    .D(\uart_baud.tx_acc [3]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(\uart_baud.tx_acc [4]),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__and4_1 _253_ (
    .A(\uart_baud.tx_acc [4]),
    .B(\uart_baud.tx_acc [5]),
    .C(\uart_baud.tx_acc [6]),
    .D(_098_),
    .X(_100_)
  );
  sky130_fd_sc_hd__a31oi_1 _254_ (
    .A1(\uart_baud.tx_acc [4]),
    .A2(\uart_baud.tx_acc [5]),
    .A3(_098_),
    .B1(\uart_baud.tx_acc [6]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(_100_),
    .B(_101_),
    .Y(_001_[6])
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(\uart_rx.state [1]),
    .B(\uart_rx.state [0]),
    .Y(\_140_$func$synth_uart_audhi.v:609$177.$result [0])
  );
  sky130_fd_sc_hd__clkinv_1 _257_ (
    .A(\_140_$func$synth_uart_audhi.v:609$177.$result [0]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2b_1 _258_ (
    .A(\uart_rx.state [1]),
    .B_N(\uart_rx.state [0]),
    .Y(\_140_$func$synth_uart_audhi.v:609$177.$result [1])
  );
  sky130_fd_sc_hd__nor3b_1 _259_ (
    .A(\uart_rx.state [0]),
    .B(_078_),
    .C_N(\uart_rx.state [1]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(\uart_rx.bitpos [1]),
    .B(\uart_rx.bitpos [0]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor3_1 _261_ (
    .A(\uart_rx.bitpos [2]),
    .B(\uart_rx.bitpos [1]),
    .C(\uart_rx.bitpos [0]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand3_1 _262_ (
    .A(\uart_rx.bitpos [3]),
    .B(_077_),
    .C(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21bai_1 _263_ (
    .A1(_077_),
    .A2(_144_),
    .B1_N(_095_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a211oi_1 _264_ (
    .A1(\_140_$func$synth_uart_audhi.v:609$177.$result [1]),
    .A2(_105_),
    .B1(_106_),
    .C1(_102_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_081_),
    .B(\_140_$func$synth_uart_audhi.v:609$177.$result [0]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor3_1 _266_ (
    .A(\uart_rx.sample [2]),
    .B(\uart_rx.sample [3]),
    .C(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a221oi_1 _267_ (
    .A1(\uart_rx.state [1]),
    .A2(\uart_rx.state [0]),
    .B1(_108_),
    .B2(rx),
    .C1(_095_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(\uart_rx.bitpos [1]),
    .B(\uart_rx.bitpos [0]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _269_ (
    .A(\uart_rx.bitpos [2]),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _270_ (
    .A(\uart_rx.bitpos [2]),
    .B(_109_),
    .Y(_009_[2])
  );
  sky130_fd_sc_hd__nand3_1 _271_ (
    .A(\uart_rx.bitpos [2]),
    .B(\uart_rx.bitpos [1]),
    .C(\uart_rx.bitpos [0]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _272_ (
    .A(\uart_rx.bitpos [3]),
    .B(_111_),
    .Y(_009_[3])
  );
  sky130_fd_sc_hd__xor2_1 _273_ (
    .A(\uart_baud.tx_acc [0]),
    .B(\uart_baud.tx_acc [1]),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _274_ (
    .A1(\uart_baud.tx_acc [0]),
    .A2(\uart_baud.tx_acc [1]),
    .B1(\uart_baud.tx_acc [2]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_097_),
    .B(_112_),
    .Y(_001_[2])
  );
  sky130_fd_sc_hd__xor2_1 _276_ (
    .A(\uart_baud.tx_acc [3]),
    .B(_097_),
    .X(_001_[3])
  );
  sky130_fd_sc_hd__xor2_1 _277_ (
    .A(\uart_baud.tx_acc [4]),
    .B(_098_),
    .X(_001_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(\uart_baud.tx_acc [5]),
    .B(_099_),
    .Y(_001_[5])
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(\uart_baud.tx_acc [7]),
    .B(_100_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _280_ (
    .A(\uart_baud.tx_acc [7]),
    .B(_100_),
    .X(_001_[7])
  );
  sky130_fd_sc_hd__nand3_1 _281_ (
    .A(\uart_baud.tx_acc [7]),
    .B(\uart_baud.tx_acc [8]),
    .C(_100_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__xnor2_1 _282_ (
    .A(\uart_baud.tx_acc [8]),
    .B(_113_),
    .Y(_001_[8])
  );
  sky130_fd_sc_hd__nand4_1 _283_ (
    .A(\uart_baud.tx_acc [7]),
    .B(\uart_baud.tx_acc [8]),
    .C(\uart_baud.tx_acc [9]),
    .D(_100_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(\uart_baud.tx_acc [9]),
    .B(_114_),
    .Y(_001_[9])
  );
  sky130_fd_sc_hd__xnor2_1 _285_ (
    .A(\uart_baud.tx_acc [10]),
    .B(_115_),
    .Y(_001_[10])
  );
  sky130_fd_sc_hd__xor2_1 _286_ (
    .A(\uart_tx.bitpos [0]),
    .B(\uart_tx.bitpos [1]),
    .X(_057_[1])
  );
  sky130_fd_sc_hd__and3_1 _287_ (
    .A(\uart_tx.bitpos [0]),
    .B(\uart_tx.bitpos [1]),
    .C(\uart_tx.bitpos [2]),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(\uart_tx.bitpos [0]),
    .A2(\uart_tx.bitpos [1]),
    .B1(\uart_tx.bitpos [2]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_116_),
    .B(_117_),
    .Y(_057_[2])
  );
  sky130_fd_sc_hd__xor2_1 _290_ (
    .A(\uart_baud.rx_acc [0]),
    .B(\uart_baud.rx_acc [1]),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__and3_1 _291_ (
    .A(\uart_baud.rx_acc [0]),
    .B(\uart_baud.rx_acc [1]),
    .C(\uart_baud.rx_acc [2]),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(\uart_baud.rx_acc [0]),
    .A2(\uart_baud.rx_acc [1]),
    .B1(\uart_baud.rx_acc [2]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_118_),
    .B(_119_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(\uart_baud.rx_acc [3]),
    .B(_118_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xor2_1 _295_ (
    .A(\uart_baud.rx_acc [3]),
    .B(_118_),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__nand3_1 _296_ (
    .A(\uart_baud.rx_acc [3]),
    .B(\uart_baud.rx_acc [4]),
    .C(_118_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _297_ (
    .A(\uart_baud.rx_acc [4]),
    .B(_120_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__nand4_1 _298_ (
    .A(\uart_baud.rx_acc [3]),
    .B(\uart_baud.rx_acc [4]),
    .C(\uart_baud.rx_acc [5]),
    .D(_118_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(\uart_baud.rx_acc [5]),
    .B(_121_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__xnor2_1 _300_ (
    .A(\uart_baud.rx_acc [6]),
    .B(_122_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(\uart_rx.scratch [0]),
    .B(_104_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _302_ (
    .A1(_073_),
    .A2(_104_),
    .B1(_123_),
    .Y(_007_[0])
  );
  sky130_fd_sc_hd__nor3_1 _303_ (
    .A(\uart_rx.bitpos [2]),
    .B(\uart_rx.bitpos [1]),
    .C(_009_[0]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _304_ (
    .A(\uart_rx.scratch [1]),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _305_ (
    .A1(_073_),
    .A2(_124_),
    .B1(_125_),
    .Y(_007_[1])
  );
  sky130_fd_sc_hd__nor3b_1 _306_ (
    .A(\uart_rx.bitpos [2]),
    .B(\uart_rx.bitpos [0]),
    .C_N(\uart_rx.bitpos [1]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _307_ (
    .A(\uart_rx.scratch [2]),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _308_ (
    .A1(_073_),
    .A2(_126_),
    .B1(_127_),
    .Y(_007_[2])
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(\uart_rx.scratch [3]),
    .B(_110_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(_073_),
    .A2(_110_),
    .B1(_128_),
    .Y(_007_[3])
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(\uart_rx.bitpos [2]),
    .A2(_103_),
    .B1(\uart_rx.scratch [4]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a31oi_1 _312_ (
    .A1(\uart_rx.bitpos [2]),
    .A2(_073_),
    .A3(_103_),
    .B1(_129_),
    .Y(_007_[4])
  );
  sky130_fd_sc_hd__nand3b_1 _313_ (
    .A_N(\uart_rx.bitpos [1]),
    .B(\uart_rx.bitpos [0]),
    .C(\uart_rx.bitpos [2]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(\uart_rx.scratch [5]),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o21ai_0 _315_ (
    .A1(_073_),
    .A2(_130_),
    .B1(_131_),
    .Y(_007_[5])
  );
  sky130_fd_sc_hd__nand3_1 _316_ (
    .A(\uart_rx.bitpos [2]),
    .B(\uart_rx.bitpos [1]),
    .C(_009_[0]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _317_ (
    .A(\uart_rx.scratch [6]),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _318_ (
    .A1(_073_),
    .A2(_132_),
    .B1(_133_),
    .Y(_007_[6])
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(\uart_rx.scratch [7]),
    .B(_111_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_073_),
    .A2(_111_),
    .B1(_134_),
    .Y(_007_[7])
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(wr_en),
    .B(_096_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _322_ (
    .A(_135_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(\uart_tx.state [0]),
    .B(_116_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor4_1 _324_ (
    .A(\uart_baud.tx_acc [2]),
    .B(\uart_baud.tx_acc [3]),
    .C(\uart_baud.tx_acc [6]),
    .D(\uart_baud.tx_acc [7]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor3_1 _325_ (
    .A(\uart_baud.tx_acc [5]),
    .B(\uart_baud.tx_acc [8]),
    .C(\uart_baud.tx_acc [9]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor4_1 _326_ (
    .A(\uart_baud.tx_acc [0]),
    .B(\uart_baud.tx_acc [4]),
    .C(\uart_baud.tx_acc [10]),
    .D(\uart_baud.tx_acc [1]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand3_1 _327_ (
    .A(_137_),
    .B(_138_),
    .C(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_096_),
    .B(_140_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o31ai_1 _329_ (
    .A1(_096_),
    .A2(_136_),
    .A3(_140_),
    .B1(_135_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o31ai_1 _330_ (
    .A1(_084_),
    .A2(_116_),
    .A3(_140_),
    .B1(_135_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__or4b_1 _331_ (
    .A(_000_[0]),
    .B(\uart_baud.rx_acc [1]),
    .C(_094_),
    .D_N(\uart_baud.rx_acc [6]),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(\uart_baud.tx_acc [4]),
    .B(\uart_baud.tx_acc [10]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3_1 _333_ (
    .A(_001_[0]),
    .B(\uart_baud.tx_acc [1]),
    .C(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_137_),
    .B(_138_),
    .C(_142_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3b_1 _335_ (
    .A_N(\uart_rx.sample [2]),
    .B(\uart_rx.sample [3]),
    .C(_081_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a211oi_1 _336_ (
    .A1(\uart_rx.state [0]),
    .A2(_143_),
    .B1(_106_),
    .C1(\uart_rx.state [1]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _337_ (
    .A(_018_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(\uart_tx.bitpos [0]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(\uart_tx.bitpos [1]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__clkinv_1 _340_ (
    .A(\uart_tx.bitpos [2]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__mux2_1 _341_ (
    .A0(\uart_tx.tx ),
    .A1(\_174_$func$synth_uart_audhi.v:662$178.$result ),
    .S(_070_),
    .X(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _342_ (
    .A0(\uart_rx.data [0]),
    .A1(\uart_rx.scratch [0]),
    .S(_019_),
    .X(_164_)
  );
  sky130_fd_sc_hd__mux2_1 _343_ (
    .A0(\uart_rx.data [1]),
    .A1(\uart_rx.scratch [1]),
    .S(_019_),
    .X(_165_)
  );
  sky130_fd_sc_hd__mux2_1 _344_ (
    .A0(\uart_rx.data [2]),
    .A1(\uart_rx.scratch [2]),
    .S(_019_),
    .X(_166_)
  );
  sky130_fd_sc_hd__mux2_1 _345_ (
    .A0(\uart_rx.data [3]),
    .A1(\uart_rx.scratch [3]),
    .S(_019_),
    .X(_167_)
  );
  sky130_fd_sc_hd__mux2_1 _346_ (
    .A0(\uart_rx.data [4]),
    .A1(\uart_rx.scratch [4]),
    .S(_019_),
    .X(_168_)
  );
  sky130_fd_sc_hd__mux2_1 _347_ (
    .A0(\uart_rx.data [5]),
    .A1(\uart_rx.scratch [5]),
    .S(_019_),
    .X(_169_)
  );
  sky130_fd_sc_hd__mux2_1 _348_ (
    .A0(\uart_rx.data [6]),
    .A1(\uart_rx.scratch [6]),
    .S(_019_),
    .X(_170_)
  );
  sky130_fd_sc_hd__mux2_1 _349_ (
    .A0(\uart_rx.data [7]),
    .A1(\uart_rx.scratch [7]),
    .S(_019_),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux2_1 _350_ (
    .A0(\uart_rx.state [0]),
    .A1(\_140_$func$synth_uart_audhi.v:609$177.$result [0]),
    .S(_020_),
    .X(_172_)
  );
  sky130_fd_sc_hd__mux2_1 _351_ (
    .A0(\uart_rx.state [1]),
    .A1(\_140_$func$synth_uart_audhi.v:609$177.$result [1]),
    .S(_020_),
    .X(_173_)
  );
  sky130_fd_sc_hd__mux2_1 _352_ (
    .A0(\uart_rx.sample [0]),
    .A1(\_136_$func$synth_uart_audhi.v:590$176.$result [0]),
    .S(_021_),
    .X(_174_)
  );
  sky130_fd_sc_hd__mux2_1 _353_ (
    .A0(\uart_rx.sample [1]),
    .A1(\_136_$func$synth_uart_audhi.v:590$176.$result [1]),
    .S(_021_),
    .X(_175_)
  );
  sky130_fd_sc_hd__mux2_1 _354_ (
    .A0(\uart_rx.sample [2]),
    .A1(\_136_$func$synth_uart_audhi.v:590$176.$result [2]),
    .S(_021_),
    .X(_176_)
  );
  sky130_fd_sc_hd__and2_0 _355_ (
    .A(_018_),
    .B(_144_),
    .X(_207_)
  );
  sky130_fd_sc_hd__a22o_1 _356_ (
    .A1(\uart_rx.bitpos [0]),
    .A2(_203_),
    .B1(_009_[0]),
    .B2(_207_),
    .X(_177_)
  );
  sky130_fd_sc_hd__a22o_1 _357_ (
    .A1(_203_),
    .A2(\uart_rx.bitpos [1]),
    .B1(_009_[1]),
    .B2(_207_),
    .X(_178_)
  );
  sky130_fd_sc_hd__a22o_1 _358_ (
    .A1(_203_),
    .A2(\uart_rx.bitpos [2]),
    .B1(_009_[2]),
    .B2(_207_),
    .X(_179_)
  );
  sky130_fd_sc_hd__a22o_1 _359_ (
    .A1(_203_),
    .A2(\uart_rx.bitpos [3]),
    .B1(_009_[3]),
    .B2(_207_),
    .X(_180_)
  );
  sky130_fd_sc_hd__mux2_1 _360_ (
    .A0(\uart_rx.sample [3]),
    .A1(\_136_$func$synth_uart_audhi.v:590$176.$result [3]),
    .S(_021_),
    .X(_181_)
  );
  sky130_fd_sc_hd__mux2_1 _361_ (
    .A0(\uart_tx.data [0]),
    .A1(din[0]),
    .S(_067_),
    .X(_182_)
  );
  sky130_fd_sc_hd__mux2_1 _362_ (
    .A0(\uart_tx.data [1]),
    .A1(din[1]),
    .S(_067_),
    .X(_183_)
  );
  sky130_fd_sc_hd__mux2_1 _363_ (
    .A0(\uart_tx.data [2]),
    .A1(din[2]),
    .S(_067_),
    .X(_184_)
  );
  sky130_fd_sc_hd__mux2_1 _364_ (
    .A0(\uart_tx.data [3]),
    .A1(din[3]),
    .S(_067_),
    .X(_185_)
  );
  sky130_fd_sc_hd__mux2_1 _365_ (
    .A0(\uart_tx.data [4]),
    .A1(din[4]),
    .S(_067_),
    .X(_186_)
  );
  sky130_fd_sc_hd__mux2_1 _366_ (
    .A0(\uart_tx.data [5]),
    .A1(din[5]),
    .S(_067_),
    .X(_187_)
  );
  sky130_fd_sc_hd__mux2_1 _367_ (
    .A0(\uart_tx.data [6]),
    .A1(din[6]),
    .S(_067_),
    .X(_188_)
  );
  sky130_fd_sc_hd__mux2_1 _368_ (
    .A0(\uart_tx.data [7]),
    .A1(din[7]),
    .S(_067_),
    .X(_189_)
  );
  sky130_fd_sc_hd__mux2_1 _369_ (
    .A0(\uart_tx.state [0]),
    .A1(\_182_$func$synth_uart_audhi.v:700$180.$result [0]),
    .S(_068_),
    .X(_190_)
  );
  sky130_fd_sc_hd__a22o_1 _370_ (
    .A1(\uart_rx.scratch [0]),
    .A2(_203_),
    .B1(_007_[0]),
    .B2(_207_),
    .X(_191_)
  );
  sky130_fd_sc_hd__a22o_1 _371_ (
    .A1(\uart_rx.scratch [1]),
    .A2(_203_),
    .B1(_007_[1]),
    .B2(_207_),
    .X(_192_)
  );
  sky130_fd_sc_hd__a22o_1 _372_ (
    .A1(\uart_rx.scratch [2]),
    .A2(_203_),
    .B1(_007_[2]),
    .B2(_207_),
    .X(_193_)
  );
  sky130_fd_sc_hd__a22o_1 _373_ (
    .A1(\uart_rx.scratch [3]),
    .A2(_203_),
    .B1(_007_[3]),
    .B2(_207_),
    .X(_194_)
  );
  sky130_fd_sc_hd__a22o_1 _374_ (
    .A1(\uart_rx.scratch [4]),
    .A2(_203_),
    .B1(_007_[4]),
    .B2(_207_),
    .X(_195_)
  );
  sky130_fd_sc_hd__a22o_1 _375_ (
    .A1(\uart_rx.scratch [5]),
    .A2(_203_),
    .B1(_007_[5]),
    .B2(_207_),
    .X(_196_)
  );
  sky130_fd_sc_hd__a22o_1 _376_ (
    .A1(\uart_rx.scratch [6]),
    .A2(_203_),
    .B1(_007_[6]),
    .B2(_207_),
    .X(_197_)
  );
  sky130_fd_sc_hd__a22o_1 _377_ (
    .A1(\uart_rx.scratch [7]),
    .A2(_203_),
    .B1(_007_[7]),
    .B2(_207_),
    .X(_198_)
  );
  sky130_fd_sc_hd__mux2_1 _378_ (
    .A0(\uart_tx.state [1]),
    .A1(\_182_$func$synth_uart_audhi.v:700$180.$result [1]),
    .S(_068_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nand3_1 _379_ (
    .A(_069_),
    .B(tx_busy),
    .C(_057_[0]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _380_ (
    .A1(_204_),
    .A2(_069_),
    .B1(_208_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand3_1 _381_ (
    .A(_069_),
    .B(tx_busy),
    .C(_057_[1]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__o21ai_0 _382_ (
    .A1(_069_),
    .A2(_205_),
    .B1(_209_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand3_1 _383_ (
    .A(_069_),
    .B(tx_busy),
    .C(_057_[2]),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21ai_0 _384_ (
    .A1(_069_),
    .A2(_206_),
    .B1(_210_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__and2_0 _385_ (
    .A(_072_),
    .B(_001_[0]),
    .X(_146_)
  );
  sky130_fd_sc_hd__and2_0 _386_ (
    .A(_072_),
    .B(_001_[1]),
    .X(_147_)
  );
  sky130_fd_sc_hd__and2_0 _387_ (
    .A(_072_),
    .B(_001_[2]),
    .X(_148_)
  );
  sky130_fd_sc_hd__and2_0 _388_ (
    .A(_072_),
    .B(_001_[3]),
    .X(_149_)
  );
  sky130_fd_sc_hd__and2_0 _389_ (
    .A(_072_),
    .B(_001_[4]),
    .X(_150_)
  );
  sky130_fd_sc_hd__and2_0 _390_ (
    .A(_072_),
    .B(_001_[5]),
    .X(_151_)
  );
  sky130_fd_sc_hd__and2_0 _391_ (
    .A(_072_),
    .B(_001_[6]),
    .X(_152_)
  );
  sky130_fd_sc_hd__and2_0 _392_ (
    .A(_072_),
    .B(_001_[7]),
    .X(_153_)
  );
  sky130_fd_sc_hd__and2_0 _393_ (
    .A(_072_),
    .B(_001_[8]),
    .X(_154_)
  );
  sky130_fd_sc_hd__and2_0 _394_ (
    .A(_072_),
    .B(_001_[9]),
    .X(_155_)
  );
  sky130_fd_sc_hd__and2_0 _395_ (
    .A(_072_),
    .B(_001_[10]),
    .X(_156_)
  );
  sky130_fd_sc_hd__and2_0 _396_ (
    .A(_071_),
    .B(_000_[0]),
    .X(_157_)
  );
  sky130_fd_sc_hd__and2_0 _397_ (
    .A(_071_),
    .B(_000_[1]),
    .X(_158_)
  );
  sky130_fd_sc_hd__and2_0 _398_ (
    .A(_071_),
    .B(_000_[2]),
    .X(_159_)
  );
  sky130_fd_sc_hd__and2_0 _399_ (
    .A(_071_),
    .B(_000_[3]),
    .X(_160_)
  );
  sky130_fd_sc_hd__and2_0 _400_ (
    .A(_071_),
    .B(_000_[4]),
    .X(_161_)
  );
  sky130_fd_sc_hd__and2_0 _401_ (
    .A(_071_),
    .B(_000_[5]),
    .X(_162_)
  );
  sky130_fd_sc_hd__and2_0 _402_ (
    .A(_071_),
    .B(_000_[6]),
    .X(_163_)
  );
  sky130_fd_sc_hd__dfxtp_1 _403_ (
    .CLK(clk_5m),
    .D(_145_),
    .Q(\uart_tx.tx )
  );
  sky130_fd_sc_hd__dfxtp_1 _404_ (
    .CLK(clk_5m),
    .D(_146_),
    .Q(\uart_baud.tx_acc [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _405_ (
    .CLK(clk_5m),
    .D(_147_),
    .Q(\uart_baud.tx_acc [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _406_ (
    .CLK(clk_5m),
    .D(_148_),
    .Q(\uart_baud.tx_acc [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _407_ (
    .CLK(clk_5m),
    .D(_149_),
    .Q(\uart_baud.tx_acc [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _408_ (
    .CLK(clk_5m),
    .D(_150_),
    .Q(\uart_baud.tx_acc [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _409_ (
    .CLK(clk_5m),
    .D(_151_),
    .Q(\uart_baud.tx_acc [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _410_ (
    .CLK(clk_5m),
    .D(_152_),
    .Q(\uart_baud.tx_acc [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _411_ (
    .CLK(clk_5m),
    .D(_153_),
    .Q(\uart_baud.tx_acc [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _412_ (
    .CLK(clk_5m),
    .D(_154_),
    .Q(\uart_baud.tx_acc [8])
  );
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(clk_5m),
    .D(_155_),
    .Q(\uart_baud.tx_acc [9])
  );
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(clk_5m),
    .D(_156_),
    .Q(\uart_baud.tx_acc [10])
  );
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(clk_5m),
    .D(_157_),
    .Q(\uart_baud.rx_acc [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _416_ (
    .CLK(clk_5m),
    .D(_158_),
    .Q(\uart_baud.rx_acc [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _417_ (
    .CLK(clk_5m),
    .D(_159_),
    .Q(\uart_baud.rx_acc [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(clk_5m),
    .D(_160_),
    .Q(\uart_baud.rx_acc [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(clk_5m),
    .D(_161_),
    .Q(\uart_baud.rx_acc [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(clk_5m),
    .D(_162_),
    .Q(\uart_baud.rx_acc [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _421_ (
    .CLK(clk_5m),
    .D(_163_),
    .Q(\uart_baud.rx_acc [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(clk_5m),
    .D(_164_),
    .Q(\uart_rx.data [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clk_5m),
    .D(_165_),
    .Q(\uart_rx.data [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clk_5m),
    .D(_166_),
    .Q(\uart_rx.data [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clk_5m),
    .D(_167_),
    .Q(\uart_rx.data [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _426_ (
    .CLK(clk_5m),
    .D(_168_),
    .Q(\uart_rx.data [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _427_ (
    .CLK(clk_5m),
    .D(_169_),
    .Q(\uart_rx.data [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _428_ (
    .CLK(clk_5m),
    .D(_170_),
    .Q(\uart_rx.data [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _429_ (
    .CLK(clk_5m),
    .D(_171_),
    .Q(\uart_rx.data [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _430_ (
    .CLK(clk_5m),
    .D(_172_),
    .Q(\uart_rx.state [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _431_ (
    .CLK(clk_5m),
    .D(_173_),
    .Q(\uart_rx.state [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _432_ (
    .CLK(clk_5m),
    .D(_174_),
    .Q(\uart_rx.sample [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _433_ (
    .CLK(clk_5m),
    .D(_175_),
    .Q(\uart_rx.sample [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _434_ (
    .CLK(clk_5m),
    .D(_176_),
    .Q(\uart_rx.sample [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _435_ (
    .CLK(clk_5m),
    .D(_177_),
    .Q(\uart_rx.bitpos [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _436_ (
    .CLK(clk_5m),
    .D(_178_),
    .Q(\uart_rx.bitpos [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _437_ (
    .CLK(clk_5m),
    .D(_179_),
    .Q(\uart_rx.bitpos [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _438_ (
    .CLK(clk_5m),
    .D(_180_),
    .Q(\uart_rx.bitpos [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _439_ (
    .CLK(clk_5m),
    .D(_181_),
    .Q(\uart_rx.sample [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _440_ (
    .CLK(clk_5m),
    .D(_182_),
    .Q(\uart_tx.data [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _441_ (
    .CLK(clk_5m),
    .D(_183_),
    .Q(\uart_tx.data [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _442_ (
    .CLK(clk_5m),
    .D(_184_),
    .Q(\uart_tx.data [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _443_ (
    .CLK(clk_5m),
    .D(_185_),
    .Q(\uart_tx.data [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _444_ (
    .CLK(clk_5m),
    .D(_186_),
    .Q(\uart_tx.data [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _445_ (
    .CLK(clk_5m),
    .D(_187_),
    .Q(\uart_tx.data [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _446_ (
    .CLK(clk_5m),
    .D(_188_),
    .Q(\uart_tx.data [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _447_ (
    .CLK(clk_5m),
    .D(_004_),
    .Q(\uart_rx.rdy )
  );
  sky130_fd_sc_hd__dfxtp_1 _448_ (
    .CLK(clk_5m),
    .D(_189_),
    .Q(\uart_tx.data [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _449_ (
    .CLK(clk_5m),
    .D(_190_),
    .Q(\uart_tx.state [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _450_ (
    .CLK(clk_5m),
    .D(_191_),
    .Q(\uart_rx.scratch [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _451_ (
    .CLK(clk_5m),
    .D(_192_),
    .Q(\uart_rx.scratch [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _452_ (
    .CLK(clk_5m),
    .D(_193_),
    .Q(\uart_rx.scratch [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _453_ (
    .CLK(clk_5m),
    .D(_194_),
    .Q(\uart_rx.scratch [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _454_ (
    .CLK(clk_5m),
    .D(_195_),
    .Q(\uart_rx.scratch [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _455_ (
    .CLK(clk_5m),
    .D(_196_),
    .Q(\uart_rx.scratch [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _456_ (
    .CLK(clk_5m),
    .D(_197_),
    .Q(\uart_rx.scratch [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _457_ (
    .CLK(clk_5m),
    .D(_198_),
    .Q(\uart_rx.scratch [7])
  );
  sky130_fd_sc_hd__dfxtp_1 _458_ (
    .CLK(clk_5m),
    .D(_199_),
    .Q(\uart_tx.state [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _459_ (
    .CLK(clk_5m),
    .D(_200_),
    .Q(\uart_tx.bitpos [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _460_ (
    .CLK(clk_5m),
    .D(_201_),
    .Q(\uart_tx.bitpos [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _461_ (
    .CLK(clk_5m),
    .D(_202_),
    .Q(\uart_tx.bitpos [2])
  );
  assign \_131_$func$synth_uart_audhi.v:557$181.b  = 16'hxxxx;
  assign \_131_$func$synth_uart_audhi.v:557$181.s  = 2'hx;
  assign \_133_$func$synth_uart_audhi.v:572$182.b  = 8'hxx;
  assign \_133_$func$synth_uart_audhi.v:572$182.s  = 2'hx;
  assign \_136_$func$synth_uart_audhi.v:590$183.b  = 12'hxxx;
  assign \_136_$func$synth_uart_audhi.v:590$183.s  = 3'hx;
  assign \_140_$func$synth_uart_audhi.v:609$184.b  = 6'hxx;
  assign \_140_$func$synth_uart_audhi.v:609$184.s  = 3'hx;
  assign \_174_$func$synth_uart_audhi.v:662$185.b  = 3'hx;
  assign \_174_$func$synth_uart_audhi.v:662$185.s  = 3'hx;
  assign \_179_$func$synth_uart_audhi.v:680$186.b  = 6'hxx;
  assign \_179_$func$synth_uart_audhi.v:680$186.s  = 2'hx;
  assign \_182_$func$synth_uart_audhi.v:700$187.b  = 8'hxx;
  assign \_182_$func$synth_uart_audhi.v:700$187.s  = 4'hx;
  assign dout = \uart_rx.data ;
  assign rdy = \uart_rx.rdy ;
  assign tx = \uart_tx.tx ;
  assign \uart_baud.clk_5m  = clk_5m;
  assign \uart_rx.clk_5m  = clk_5m;
  assign \uart_rx.rdy_clr  = rdy_clr;
  assign \uart_rx.rx  = rx;
  assign \uart_tx.clk_5m  = clk_5m;
  assign \uart_tx.din  = din;
  assign \uart_tx.tx_busy  = tx_busy;
  assign \uart_tx.wr_en  = wr_en;
endmodule
